### ISSUE TITLE
lol 13.16

### ISSUE THREAD

**Issue by 4sai2** [JerryLiew/LeagueBackupper#1]
i have 13.13 file, but i wanna watch 13.16 replay for replaybook. please help me... My adress: wkddudwo2@gmail.com

**Comment by JerryLiew** [comment]
I'm not sure if I have the corresponding version of the client. When I come home from work, I'll take a look

**Comment by JerryLiew** [comment]
I have the client with version 13.16.525.6433, but it's Chinese version, so I am not sure if it will work for you. by the way, The size of the entire game directory exceeds 20GB, and I also don't know how to send it to you.

**Comment by 4sai2** [comment]
Please compress only the "Game" folder in the "League of Legends" folder using ZIP, etc., upload it to "https://file.kiwi/" (no 'sign up' or installaton required), and send me the URL. No further action is required, but do not close the window until it is uploaded. Thank you very much.

**Comment by JerryLiew** [comment]
> Please compress only the "Game" folder in the "League of Legends" folder using ZIP, etc., upload it to "https://file.kiwi/" (no 'sign up' and installaton required), and send me the URL. No further action is required, but do not close the window until it is uploaded. Thank you very much.
ok, i will give it a shot after work and hope that the upload speed won't be too slow when uploading files from China.

**Comment by 4sai2** [comment]
thanks. If possible, please send me the full folder of 'lol'.

**Comment by JerryLiew** [comment]
![image](https://github.com/JerryLiew/LeagueBackupper/assets/51161678/10d5681a-ac5c-4cee-a7bb-ceed2fc20cf7)
https://file.kiwi/
This website does not work anymore for me. No matter how I try, it always displays the loading animation and then returns to the initial state after a while.

**Comment by JerryLiew** [comment]
Is there any other way? If not, I will start a http web file server, and i will tell you the URL of that, then you can download it by yourself.

**Comment by 4sai2** [comment]
Thank you so much for your kindness.. Please do

**Comment by JerryLiew** [comment]
here's the download url, [download url](http://117.67.77.171:9009/share/nLrzg6y7 )
Please notify me after completing the download task so that I can shut down the server.

**Comment by 4sai2** [comment]
I did. Thank you.
