### ISSUE TITLE
Possible to make it like League-VCS ?

### ISSUE THREAD

**Issue by JustSxm** [JerryLiew/LeagueBackupper#2]
League-VCS hasn't been updated in a while,

It would be cool if we could have the "automatic" scanning where we dont need to do anything and can switch easily between versions with a GUI.

**Comment by JerryLiew** [comment]
The main goal of this tool is to reduce the hard disk occupation of the storage client, so it is very slow in storing or restoring the client files. At the same time, it will also have a high hard disk occupation when working, which will bring computer stagnation, so it is not suitable for making the form of automatic scanning and processing in the background. LeagueVCS is a less expensive and faster option if you only want to store different clients and don't care about the disk space usage.
